### PR TITLE
sphinx-book-theme 0.1.0, update dependencies, add tests with coverage, update metadata, add jupyter-book maintainers

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.
  * [x] remove vendored license, point at distributed one

Notes
- includes #9
- unblocks https://github.com/conda-forge/jupyter-book-feedstock/pull/5
- adds tests with coverage threshold (currently 87 on linux)
- updates metadata to point at actual docs for _this_ package, etc.
- adds @conda-forge/jupyter-book as a maintainer: I accept responsibility on our behalf

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/sphinx-book-theme ready for review!

**Comment by AakashGfude** [comment]
@bollwyvl is it ready to be merged?

**Comment by choldgraf** [comment]
I don't have permissions to merge this in, but I think we should just do it so that the conda and pip versions aren't too out of sync. can the @conda-forge/sphinx-book-theme people add me and @AakashGfude as admins, or merge this yourselves?

**Comment by bollwyvl** [comment]
> is it ready to be merged?

Yeah, sorry, didn't see this: it is ready for review.

> people add me

This pr would already add everyone from @conda-forge/jupyter-book (symbolically). and indeed, given the aggressive pins on all these things, for any upstream on conda-forge, some shared maintenance will probably help...

**Comment by chrisjsewell** [comment]
Heya, why do you think we should now be running the full test suite with coverage?
Not saying I’m definitely against it, but this seems like a “change in policy” from our current practice across EBP packages of simply running pip check, and relying on the upload to pypi to be fully tested (which they are).

Is there examples of other conda packages doing this?

**Comment by bollwyvl** [comment]
> why do you think we should now be running the full test suite with coverage?

Running the tests empirically _finds bugs_, especially packaging ones, and even small things like version mismatches can ruin a user's day. Further, unless someone goes and reads the entire log, it's possible for simple smoke tests to start throwing helpful warnings, which are ignored. When feasible, the full test suite, with coverage, means that when the bot says a build is green, _it's green_. From a maintainer perspective, adding these tests here (having already sunk the cost) means that each incremental PR is easier and more confident to review. This is important at the scale of e.g. all of the jupyter packages, etc.  to keep fresh packages coming out in a timely manner.

> Is there examples of other conda packages doing this?

Yeah. As much of the jupyter stack as is feasible, for instance. When I get involved with a feedstock and it _ever_ has a packaging issue reported by a downstream, I try to add the tests, and finding issues as deep in a given stack is very helpful, especially when coordinated releases go out.

> pypi to be fully tested

Fully tested _at that time_, against _whatever that test suite CI_ happened to have installed, which may have been even more tightly pinned. And very likely _not_ against only conda-forge packages. These are all conditions that can just be ignored if the full test suite runs well.

**Pull request merged**
